// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $bcrypt_forgot_password_index from "./routes/bcrypt/forgot-password/index.tsx";
import * as $bcrypt_forgot_password_reset_token_ from "./routes/bcrypt/forgot-password/reset/[token].tsx";
import * as $bcrypt_login from "./routes/bcrypt/login.tsx";
import * as $bcrypt_signin from "./routes/bcrypt/signin.tsx";
import * as $db_delete from "./routes/db/delete.tsx";
import * as $db_list_all from "./routes/db/list-all.tsx";
import * as $docs_01_understanding_auth from "./routes/docs/01-understanding-auth.tsx";
import * as $docs_02_sessions from "./routes/docs/02-sessions.tsx";
import * as $docs_03_cookies from "./routes/docs/03-cookies.tsx";
import * as $index from "./routes/index.tsx";
import * as $model_Data from "./routes/model/Data.ts";
import * as $model_User from "./routes/model/User.ts";
import * as $MyIsland from "./islands/MyIsland.tsx";
import * as $SessionCountdown from "./islands/SessionCountdown.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/bcrypt/forgot-password/index.tsx": $bcrypt_forgot_password_index,
    "./routes/bcrypt/forgot-password/reset/[token].tsx":
      $bcrypt_forgot_password_reset_token_,
    "./routes/bcrypt/login.tsx": $bcrypt_login,
    "./routes/bcrypt/signin.tsx": $bcrypt_signin,
    "./routes/db/delete.tsx": $db_delete,
    "./routes/db/list-all.tsx": $db_list_all,
    "./routes/docs/01-understanding-auth.tsx": $docs_01_understanding_auth,
    "./routes/docs/02-sessions.tsx": $docs_02_sessions,
    "./routes/docs/03-cookies.tsx": $docs_03_cookies,
    "./routes/index.tsx": $index,
    "./routes/model/Data.ts": $model_Data,
    "./routes/model/User.ts": $model_User,
  },
  islands: {
    "./islands/MyIsland.tsx": $MyIsland,
    "./islands/SessionCountdown.tsx": $SessionCountdown,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
